/* tslint:disable */
/* eslint-disable */
/**
 * Enterprise Connection Adapter
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

export interface HTTPValidationError {
    'detail'?: Array<ValidationError>;
}
export interface Job {
    'id': string;
    'signed_url': string;
    'file_name': string;
    'policy_packs': Array<string>;
    'file_size'?: number | null;
    'enhanced_privacy_mode'?: boolean;
}
export interface LocationInner {
}
/**
 * Request body for signed URL batch processing.  Attributes:     jobs            (List[Job]):      List of signed URL jobs.
 */
export interface SignedUrlPayload {
    'jobs': Array<Job>;
}
export interface ValidationError {
    'loc': Array<LocationInner>;
    'msg': string;
    'type': string;
    'input'?: any;
    'ctx'?: object;
}

/**
 * ChatApi - axios parameter creator
 */
export const ChatApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Firewall text chat endpoint
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adapterChat: async (requestBody: { [key: string]: any; }, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('adapterChat', 'requestBody', requestBody)
            const localVarPath = `/ai-firewall/firewall/v1/prompt/text`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * ChatApi - functional programming interface
 */
export const ChatApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ChatApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Firewall text chat endpoint
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async adapterChat(requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.adapterChat(requestBody, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ChatApi.adapterChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ChatApi - factory interface
 */
export const ChatApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ChatApiFp(configuration)
    return {
        /**
         * 
         * @summary Firewall text chat endpoint
         * @param {{ [key: string]: any; }} requestBody 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        adapterChat(requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.adapterChat(requestBody, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * ChatApi - object-oriented interface
 */
export class ChatApi extends BaseAPI {
    /**
     * 
     * @summary Firewall text chat endpoint
     * @param {{ [key: string]: any; }} requestBody 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public adapterChat(requestBody: { [key: string]: any; }, options?: RawAxiosRequestConfig) {
        return ChatApiFp(this.configuration).adapterChat(requestBody, options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * DefaultApi - axios parameter creator
 */
export const DefaultApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Replace content in uploaded files
         * @param {SignedUrlPayload} signedUrlPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fileSanitization: async (signedUrlPayload: SignedUrlPayload, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'signedUrlPayload' is not null or undefined
            assertParamExists('fileSanitization', 'signedUrlPayload', signedUrlPayload)
            const localVarPath = `/ai-firewall/firewall/v1/file/sanitization`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(signedUrlPayload, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Multimodal chat completions
         * @param {string | null} [prompt] Free-form prompt text
         * @param {string | null} [content] Optional content payload
         * @param {string | null} [text] Optional text input
         * @param {string | null} [input] Optional input input
         * @param {File | null} [file] Generic file upload (optional)
         * @param {File | null} [docx] DOCX upload (optional)
         * @param {File | null} [pdf] PDF upload (optional)
         * @param {File | null} [image] Image upload (optional)
         * @param {File | null} [audio] Audio upload (optional)
         * @param {string | null} [model] Optional model name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        multimodalChat: async (prompt?: string | null, content?: string | null, text?: string | null, input?: string | null, file?: File | null, docx?: File | null, pdf?: File | null, image?: File | null, audio?: File | null, model?: string | null, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/ai-firewall/firewall/v1/prompt`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;
            const localVarFormParams = new ((configuration && configuration.formDataCtor) || FormData)();


            if (prompt !== undefined) { 
                localVarFormParams.append('prompt', prompt as any);
            }

            if (content !== undefined) { 
                localVarFormParams.append('content', content as any);
            }

            if (text !== undefined) { 
                localVarFormParams.append('text', text as any);
            }

            if (input !== undefined) { 
                localVarFormParams.append('input', input as any);
            }

            if (file !== undefined) { 
                localVarFormParams.append('file', file as any);
            }

            if (docx !== undefined) { 
                localVarFormParams.append('docx', docx as any);
            }

            if (pdf !== undefined) { 
                localVarFormParams.append('pdf', pdf as any);
            }

            if (image !== undefined) { 
                localVarFormParams.append('image', image as any);
            }

            if (audio !== undefined) { 
                localVarFormParams.append('audio', audio as any);
            }

            if (model !== undefined) { 
                localVarFormParams.append('model', model as any);
            }
            localVarHeaderParameter['Content-Type'] = 'multipart/form-data';
            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = localVarFormParams;

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DefaultApi - functional programming interface
 */
export const DefaultApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Replace content in uploaded files
         * @param {SignedUrlPayload} signedUrlPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async fileSanitization(signedUrlPayload: SignedUrlPayload, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<string>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.fileSanitization(signedUrlPayload, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.fileSanitization']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Multimodal chat completions
         * @param {string | null} [prompt] Free-form prompt text
         * @param {string | null} [content] Optional content payload
         * @param {string | null} [text] Optional text input
         * @param {string | null} [input] Optional input input
         * @param {File | null} [file] Generic file upload (optional)
         * @param {File | null} [docx] DOCX upload (optional)
         * @param {File | null} [pdf] PDF upload (optional)
         * @param {File | null} [image] Image upload (optional)
         * @param {File | null} [audio] Audio upload (optional)
         * @param {string | null} [model] Optional model name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async multimodalChat(prompt?: string | null, content?: string | null, text?: string | null, input?: string | null, file?: File | null, docx?: File | null, pdf?: File | null, image?: File | null, audio?: File | null, model?: string | null, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<{ [key: string]: any; }>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.multimodalChat(prompt, content, text, input, file, docx, pdf, image, audio, model, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DefaultApi.multimodalChat']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DefaultApi - factory interface
 */
export const DefaultApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DefaultApiFp(configuration)
    return {
        /**
         * 
         * @summary Replace content in uploaded files
         * @param {SignedUrlPayload} signedUrlPayload 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        fileSanitization(signedUrlPayload: SignedUrlPayload, options?: RawAxiosRequestConfig): AxiosPromise<Array<string>> {
            return localVarFp.fileSanitization(signedUrlPayload, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Multimodal chat completions
         * @param {string | null} [prompt] Free-form prompt text
         * @param {string | null} [content] Optional content payload
         * @param {string | null} [text] Optional text input
         * @param {string | null} [input] Optional input input
         * @param {File | null} [file] Generic file upload (optional)
         * @param {File | null} [docx] DOCX upload (optional)
         * @param {File | null} [pdf] PDF upload (optional)
         * @param {File | null} [image] Image upload (optional)
         * @param {File | null} [audio] Audio upload (optional)
         * @param {string | null} [model] Optional model name
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        multimodalChat(prompt?: string | null, content?: string | null, text?: string | null, input?: string | null, file?: File | null, docx?: File | null, pdf?: File | null, image?: File | null, audio?: File | null, model?: string | null, options?: RawAxiosRequestConfig): AxiosPromise<{ [key: string]: any; }> {
            return localVarFp.multimodalChat(prompt, content, text, input, file, docx, pdf, image, audio, model, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DefaultApi - object-oriented interface
 */
export class DefaultApi extends BaseAPI {
    /**
     * 
     * @summary Replace content in uploaded files
     * @param {SignedUrlPayload} signedUrlPayload 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public fileSanitization(signedUrlPayload: SignedUrlPayload, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).fileSanitization(signedUrlPayload, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Multimodal chat completions
     * @param {string | null} [prompt] Free-form prompt text
     * @param {string | null} [content] Optional content payload
     * @param {string | null} [text] Optional text input
     * @param {string | null} [input] Optional input input
     * @param {File | null} [file] Generic file upload (optional)
     * @param {File | null} [docx] DOCX upload (optional)
     * @param {File | null} [pdf] PDF upload (optional)
     * @param {File | null} [image] Image upload (optional)
     * @param {File | null} [audio] Audio upload (optional)
     * @param {string | null} [model] Optional model name
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public multimodalChat(prompt?: string | null, content?: string | null, text?: string | null, input?: string | null, file?: File | null, docx?: File | null, pdf?: File | null, image?: File | null, audio?: File | null, model?: string | null, options?: RawAxiosRequestConfig) {
        return DefaultApiFp(this.configuration).multimodalChat(prompt, content, text, input, file, docx, pdf, image, audio, model, options).then((request) => request(this.axios, this.basePath));
    }
}



